### ISSUE TITLE
How initial operating points is calculated and why it is fixed value?

### ISSUE THREAD

**Issue by akhtar3100** [TU-Delft-AI-Energy-Lab/Flexibility_Under_Low_Observability#1]
Dear Demetris,
I have a question about initial operating point of the network. How it is calculated? Why initial operating point for all network variations is the same value? As per my understanding, initial operating point normally is operating point for that particular network when FSP units are operating around their normal p,q values and do not change their load or generation to provide the flexibility. so i think for each network variation there will be  new initial operating point and then flexibility resources would change their p,q values to get flexibility region.

**Comment by Demetris-Ch** [comment]
Hi,
Thank you for your question and your interest. The initial operating point is obtained from the PandaPower results after the initial power flow is run (before applying flexibility activations). As explained in the publication, all network variations have approximately the same operating conditions in observed components (including the external grid's node). The values written in the plotting scenario files are obtained after the variations are applied and the power flow is re-run.
